services:
  elasticsearch:
    container_name: "standard-coffee-shop-elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    container_name: "standard-coffee-shop-kibana"
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    container_name: "standard-coffee-shop-filebeat"
    image: docker.elastic.co/beats/filebeat:7.12.1
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro        # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure

  standard-coffee-shop-db:
    container_name: "standard-coffee-shop-db"
    image: mysql:latest
    env_file:
      - ../.env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_DATA=$MYSQL_DATA
      - MYSQL_LOCAL_PORT=$MYSQL_LOCAL_PORT
      - MYSQL_DOCKER_PORT=$MYSQL_DOCKER_PORT
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}'
    volumes:
      - "./startup-scripts/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql"
    networks:
      - mysql-network

  standard-coffee-shop-app:
    container_name: "standard-coffee-shop-app"
    build:
      context: .
      args:
        APP_LOCAL_PORT: ${APP_LOCAL_PORT}
        APP_DOCKER_PORT: ${APP_DOCKER_PORT}
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: renanzazula/standard-coffee-shop:latest
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    env_file:
      - ../.env
    expose:
      - '${APP_DOCKER_PORT}'
    ports:
      - '${APP_DOCKER_PORT}:${APP_LOCAL_PORT}'
    depends_on:
      - standard-coffee-shop-db
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
