services:
  elasticsearch:
    container_name: "standard-coffee-shop-elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    container_name: "standard-coffee-shop-kibana"
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    container_name: "standard-coffee-shop-filebeat"
    image: docker.elastic.co/beats/filebeat:7.12.1
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro        # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
